[workspace]
members = ["projects/*"]
default-members = [
    "projects/famous-chinese",
]
exclude = [
    "projects/.DS_Store",
    "projects/wikipedia",
]

[profile.release]
lto = true
panic = "abort"
